# ============================================================
# DATASOURCE
# ============================================================

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:quarkus}
quarkus.datasource.password=${DB_PASSWORD:quarkus}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/multitenant}


# ============================================================
# HIBERNATE ORM
# ============================================================

quarkus.hibernate-orm.multitenant=SCHEMA
quarkus.hibernate-orm.schema-management.strategy=none

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true


# ============================================================
# FLYWAY
# ============================================================

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration


# ============================================================
# JWT GENERATION
# ============================================================

smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.new-token.issuer=quarkus-schema-per-tenant
smallrye.jwt.new-token.lifespan=3600


# ============================================================
# JWT VALIDATION
# ============================================================

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=quarkus-schema-per-tenant